name: Keep Codespace Alive
on:
  schedule:
    - cron: '*/30 * * * *'  # Jalankan setiap 30 menit
jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Keep Codespace Alive
        run: echo "Codespace tetap hidup!"
